@echo off
wpeinit
echo PROCESSOR_ARCHITECTURE = %PROCESSOR_ARCHITECTURE%
echo PROCESSOR_IDENTIFIER = %PROCESSOR_IDENTIFIER%
echo PROCESSOR_LEVEL = %PROCESSOR_LEVEL%
echo PROCESSOR_REVISION = %PROCESSOR_REVISION%
echo NUMBER_OF_PROCESSORS = %NUMBER_OF_PROCESSORS%
ver
drvload dwusb.inf
drvload bcm2836sdhc.inf

